name: William & Mary Robotics Club
favicon: null
layout_spectrum: 0.25542
typography_spectrum: 0.49813
author:
  name: Nicholas Rance
  email: nicholas.rance@gmail.com
navigation:
  - name: Register
    url: 'https://nickrance.typeform.com/to/Cz0xhL'
    type: external
title: Beep Boop
description: Beep Boop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#053e2b'
    - '#f3d829'
    - '#7c8228'
    - '#293900'
    - '#6c721b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
