typography_spectrum: 0.49813
color:
  brandColors:
    - '#053e2b'
    - '#f3d829'
    - '#7c8228'
    - '#293900'
    - '#6c721b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.80081
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Nicholas Rance
  email: nicholas.rance@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4130f919-23bf-4dbc-b91a-9630d0bd67f5.png
name: Robotics@WM
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Register
    url: 'https://nickrance.typeform.com/to/Cz0xhL'
    type: external
  - name: Slack Group
    url: 'https://wmrobotics.slack.com/'
    type: external
  - name: FB Group
    url: 'https://www.facebook.com/groups/563778580363252/'
    type: external
  - name: Project List
    id: a448eb54-c703-449d-a078-0cfc71ce5aa5
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9200bc73-e034-46b3-949a-dc0dbbbf0c98.png
title: ''
description: ''
purpose: []
