typography_spectrum: 0.49813
color:
  brandColors:
    - '#053e2b'
    - '#f3d829'
    - '#7c8228'
    - '#293900'
    - '#6c721b'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.80081
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Nicholas Rance
  email: nicholas.rance@gmail.com
name: William & Mary Robotics Club
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Register
    url: 'https://nickrance.typeform.com/to/Cz0xhL'
    type: external
  - name: Project List
    id: a448eb54-c703-449d-a078-0cfc71ce5aa5
    type: content
  - name: Our Github
    url: 'https://www.github.com'
    type: external
favicon: null
title: Beep Boop
description: Beep Boop
purpose: []
